// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_15 = "CgkI2MuW2sUMEAIQEQ"; // <GPGSID>
        public const string achievement_11 = "CgkI2MuW2sUMEAIQDw"; // <GPGSID>
        public const string leaderboard = "CgkI2MuW2sUMEAIQCw"; // <GPGSID>
        public const string achievement_13 = "CgkI2MuW2sUMEAIQCA"; // <GPGSID>
        public const string achievement_12 = "CgkI2MuW2sUMEAIQBw"; // <GPGSID>
        public const string achievement_9 = "CgkI2MuW2sUMEAIQEA"; // <GPGSID>
        public const string achievement_2 = "CgkI2MuW2sUMEAIQAg"; // <GPGSID>
        public const string achievement_3 = "CgkI2MuW2sUMEAIQAw"; // <GPGSID>
        public const string achievement = "CgkI2MuW2sUMEAIQAQ"; // <GPGSID>
        public const string achievement_6 = "CgkI2MuW2sUMEAIQDA"; // <GPGSID>
        public const string achievement_7 = "CgkI2MuW2sUMEAIQDQ"; // <GPGSID>
        public const string achievement_4 = "CgkI2MuW2sUMEAIQBA"; // <GPGSID>
        public const string achievement_5 = "CgkI2MuW2sUMEAIQBQ"; // <GPGSID>
        public const string achievement_8 = "CgkI2MuW2sUMEAIQDg"; // <GPGSID>
        public const string achievement_10 = "CgkI2MuW2sUMEAIQBg"; // <GPGSID>
        public const string achievement_14 = "CgkI2MuW2sUMEAIQEg"; // <GPGSID>
}